<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="electronics.aspx.cs" Inherits="sampleproject.electronics" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
            background-color: #CCFFCC;
        }
        .auto-style2 {
            width: 275px;
        }
        .auto-style3 {
            width: 275px;
            height: 26px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <table class="auto-style1" aria-hidden="False">
            <tr>
                <td colspan="2">ELECTRONICS FORM</td>
            </tr>
            <tr>
                <td class="auto-style2">TYPE :</td>
                <td>
                    <asp:DropDownList ID="ddlType" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlType_SelectedIndexChanged" >
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">BRAND :</td>
                <td>
                    <asp:DropDownList ID="ddlBrand" runat="server" AutoPostBack="True" >
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">MODEL :</td>
                <td>
                    <asp:TextBox ID="txtModel" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">DESCRIPTION :</td>
                <td>
                    <asp:TextBox ID="txtDesc" runat="server" TextMode="MultiLine"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">PRICE :</td>
                <td>
                    <asp:TextBox ID="txtPrice" runat="server" TextMode="Number"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">QUANTITY :</td>
                <td>
                    <asp:TextBox ID="txtQuantity" runat="server" TextMode="Number"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">COLORS :</td>
                <td>
                    <asp:RadioButtonList ID="rblColors" runat="server" RepeatDirection="Horizontal">
                        <asp:ListItem>blue</asp:ListItem>
                        <asp:ListItem>black</asp:ListItem>
                        <asp:ListItem>gold</asp:ListItem>
                        <asp:ListItem>rosegold</asp:ListItem>
                    </asp:RadioButtonList>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">ACCESSORIES :</td>
                <td>
                    <asp:CheckBoxList ID="cblAccessories" runat="server" RepeatDirection="Horizontal">
                        <asp:ListItem>charger</asp:ListItem>
                        <asp:ListItem>headphones</asp:ListItem>
                        <asp:ListItem>touch pen</asp:ListItem>
                        <asp:ListItem>wireless mouse</asp:ListItem>
                    </asp:CheckBoxList>
                </td>
            </tr>

            <tr>
            <td class="auto-style2">FILE UPLOAD :
                <td>

                    <asp:FileUpload ID="fu_upload" runat="server" />

                </td>
                </td>
                </tr>
            <tr>
                <td class="auto-style2" colspan="2">
                    <asp:Button ID="btnSave" runat="server" Text="save" />
&nbsp;<asp:Button ID="btnReset" runat="server" Text="reset" />
                &nbsp;<asp:Button ID="btnInsert" runat="server" OnClick="btnInsert_Click" Text="insert" />
                    <asp:Button ID="btnUpdate" runat="server" Text="Update" OnClick="btnUpdate_Click" />
                    <asp:Button ID="btnDelete" runat="server" Text="Delete" OnClick="btnDelete_Click" />
                    <asp:Button ID="btnUpload" runat="server" OnClick="btnUpload_Click" Text="upload" />
                </td>
            </tr>
            <tr>
                <td class="auto-style3" colspan="2">
                    <asp:GridView ID="gvData" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="gvData_SelectedIndexChanged">
                    </asp:GridView>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
